In [1]:
# numpy
# pip install numpy
# conda install numpy


In [2]:
import numpy as np

In [3]:
# Array creations
l=[10,20,30,40]
array=np.array(l)

In [4]:
array

array([10, 20, 30, 40])

In [5]:
print(type(array))

<class 'numpy.ndarray'>


In [6]:
l1=[[100,200,300,400],[1000,2000,3000,4000]]

In [7]:
array1=np.array(l1)

In [8]:
print(array1)

[[ 100  200  300  400]
 [1000 2000 3000 4000]]


In [9]:
array1.shape

(2, 4)

In [10]:
# random generate
# linspace()
# arange()

In [12]:
lin_val=np.linspace(10,40)

In [13]:
lin_val

array([10.        , 10.6122449 , 11.2244898 , 11.83673469, 12.44897959,
       13.06122449, 13.67346939, 14.28571429, 14.89795918, 15.51020408,
       16.12244898, 16.73469388, 17.34693878, 17.95918367, 18.57142857,
       19.18367347, 19.79591837, 20.40816327, 21.02040816, 21.63265306,
       22.24489796, 22.85714286, 23.46938776, 24.08163265, 24.69387755,
       25.30612245, 25.91836735, 26.53061224, 27.14285714, 27.75510204,
       28.36734694, 28.97959184, 29.59183673, 30.20408163, 30.81632653,
       31.42857143, 32.04081633, 32.65306122, 33.26530612, 33.87755102,
       34.48979592, 35.10204082, 35.71428571, 36.32653061, 36.93877551,
       37.55102041, 38.16326531, 38.7755102 , 39.3877551 , 40.        ])

In [14]:
lin_val=np.linspace(10,40,10)

In [15]:
lin_val

array([10.        , 13.33333333, 16.66666667, 20.        , 23.33333333,
       26.66666667, 30.        , 33.33333333, 36.66666667, 40.        ])

In [20]:
lin_val=np.linspace(10,40,10,dtype='int') # first -> start, second=end,third= number of elements

In [19]:
lin_val

array([10, 13, 16, 20, 23, 26, 30, 33, 36, 40])

In [28]:
lin_val=np.linspace(1,100,200,endpoint=False)

In [29]:
lin_val

array([ 1.   ,  1.495,  1.99 ,  2.485,  2.98 ,  3.475,  3.97 ,  4.465,
        4.96 ,  5.455,  5.95 ,  6.445,  6.94 ,  7.435,  7.93 ,  8.425,
        8.92 ,  9.415,  9.91 , 10.405, 10.9  , 11.395, 11.89 , 12.385,
       12.88 , 13.375, 13.87 , 14.365, 14.86 , 15.355, 15.85 , 16.345,
       16.84 , 17.335, 17.83 , 18.325, 18.82 , 19.315, 19.81 , 20.305,
       20.8  , 21.295, 21.79 , 22.285, 22.78 , 23.275, 23.77 , 24.265,
       24.76 , 25.255, 25.75 , 26.245, 26.74 , 27.235, 27.73 , 28.225,
       28.72 , 29.215, 29.71 , 30.205, 30.7  , 31.195, 31.69 , 32.185,
       32.68 , 33.175, 33.67 , 34.165, 34.66 , 35.155, 35.65 , 36.145,
       36.64 , 37.135, 37.63 , 38.125, 38.62 , 39.115, 39.61 , 40.105,
       40.6  , 41.095, 41.59 , 42.085, 42.58 , 43.075, 43.57 , 44.065,
       44.56 , 45.055, 45.55 , 46.045, 46.54 , 47.035, 47.53 , 48.025,
       48.52 , 49.015, 49.51 , 50.005, 50.5  , 50.995, 51.49 , 51.985,
       52.48 , 52.975, 53.47 , 53.965, 54.46 , 54.955, 55.45 , 55.945,
      

In [26]:
lin_val=np.linspace(1,100,20)

In [27]:
print(lin_val)

[  1.           6.21052632  11.42105263  16.63157895  21.84210526
  27.05263158  32.26315789  37.47368421  42.68421053  47.89473684
  53.10526316  58.31578947  63.52631579  68.73684211  73.94736842
  79.15789474  84.36842105  89.57894737  94.78947368 100.        ]


In [30]:
arr=np.arange(50) # number of elements

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [32]:
arr1=np.arange(1,50)

In [33]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [36]:
arr2=np.arange(1,50,10)

In [37]:
arr2

array([ 1, 11, 21, 31, 41])

In [42]:
np.random.random(10)

array([0.27806592, 0.44945908, 0.39892719, 0.83603566, 0.21218105,
       0.72157263, 0.14182802, 0.38128102, 0.08427106, 0.94118776])

In [45]:
for i in range(10000):
    print(np.random.random(10))

[0.09532345 0.23182317 0.92959747 0.86686704 0.75041657 0.18615774
 0.66264523 0.66187201 0.19238371 0.20491499]
[0.56952066 0.05080923 0.13467361 0.91082528 0.27513701 0.53590148
 0.91240327 0.82588039 0.53944007 0.09733988]
[0.09713672 0.24901555 0.24906598 0.90692791 0.4297761  0.28974016
 0.56229994 0.57756822 0.52943471 0.08085744]
[0.92739812 0.460577   0.59991512 0.88576679 0.73626192 0.85348429
 0.60735301 0.07810188 0.95784498 0.68163445]
[0.09444175 0.37973616 0.2617484  0.42319335 0.17946763 0.66673453
 0.99526861 0.13922866 0.66244502 0.38247887]
[0.18087452 0.06447928 0.92148586 0.41660435 0.40642998 0.7279247
 0.70505013 0.47015658 0.91024483 0.47124103]
[0.31981932 0.67832424 0.58020034 0.15103986 0.6080682  0.33670979
 0.29429163 0.6093599  0.15270863 0.17074895]
[0.45997543 0.22346743 0.90723184 0.82673675 0.30747689 0.49275764
 0.10655362 0.37978965 0.70446598 0.99532673]
[0.36472597 0.86392214 0.18242824 0.23134143 0.02089458 0.3488058
 0.83395653 0.54416894 0.562338

In [62]:
np.random.seed(1000000)
for i in range(5):
    print(np.random.random(2))

[0.98837362 0.63668447]
[0.30076255 0.85895751]
[0.05151137 0.05662395]
[0.42411855 0.58806105]
[0.11343962 0.92888968]


In [63]:
np.random.randn(10)

array([ 0.53127749,  0.52709232,  0.30519413,  0.2696932 , -0.52581012,
       -0.09125407, -0.76417053,  1.43121799, -0.95265279,  0.60053537])

In [64]:
np.random.randint(10)

5

In [65]:
np.random.randint(1,100)

92

In [66]:
np.random.rand(10)

array([0.84382314, 0.20501697, 0.88818304, 0.25927096, 0.56623616,
       0.27747963, 0.18493503, 0.44735142, 0.27972836, 0.69093322])

In [67]:

np.random.random_sample(10)

array([0.48607873, 0.25716556, 0.90917005, 0.45960506, 0.90142764,
       0.54748484, 0.27192917, 0.95198181, 0.45563307, 0.57001198])

In [69]:
# Shaping
print(np.random.rand(8).shape)

(8,)


In [71]:
#shaping
arr_2d=np.random.rand(8).reshape(2,4)

In [72]:
arr_2d

array([[0.7019598 , 0.96869752, 0.53522423, 0.17096022],
       [0.73436102, 0.56683249, 0.23263152, 0.24338844]])

In [76]:
arr_2d=np.random.rand(24).reshape(4,2,3)

In [77]:
arr_2d

array([[[0.18077292, 0.81244946, 0.13362257],
        [0.36969914, 0.90243868, 0.81032042]],

       [[0.30976561, 0.60904963, 0.20628704],
        [0.72733121, 0.09040437, 0.37319172]],

       [[0.29278584, 0.45065348, 0.19059459],
        [0.2871456 , 0.75455999, 0.04800121]],

       [[0.40977325, 0.73170681, 0.23741524],
        [0.83550792, 0.43362644, 0.09721914]]])

In [78]:
arr_2d.shape

(4, 2, 3)

In [81]:
arr_1d=arr_2d.reshape(-1)

In [82]:
arr_1d.shape

(24,)

In [86]:
# default matrix
np.zeros(9).reshape(3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [88]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [92]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [93]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [94]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])