In [1]:
import numpy as np

In [2]:
# max and min functions

In [17]:
arr=np.linspace(1,500,20,dtype='int64')

In [18]:
arr

array([  1,  27,  53,  79, 106, 132, 158, 184, 211, 237, 263, 289, 316,
       342, 368, 394, 421, 447, 473, 500], dtype=int64)

In [19]:
# max and min
arr.max()

500

In [20]:
np.max(arr)

500

In [21]:
np.min(arr)

1

In [22]:
# argmax - it will returns the index of max value from the array
# argmin - it will returns the index of min value from the array

In [25]:
arr=np.array([1,90,45,-5,34,65,89,200,101])

In [26]:
arr

array([  1,  90,  45,  -5,  34,  65,  89, 200, 101])

In [27]:
np.argmax(arr)

7

In [28]:
np.argmin(arr)

3

In [29]:
arr[np.argmax(arr)]

200

In [30]:
arr[np.argmin(arr)]

-5

In [33]:
np.zeros(4)

array([0., 0., 0., 0.])

In [34]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.ones(4)

array([1., 1., 1., 1.])

In [36]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])