In [1]:
import numpy as np

In [2]:
ar=np.arange(10)

In [3]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
ar[0]

0

In [5]:
ar1=ar.reshape(5,2)

In [6]:
ar1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [7]:
ar1[0]

array([0, 1])

In [8]:
ar1[1]

array([2, 3])

In [9]:
ar2=np.arange(20).reshape(4,5)

In [12]:
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
ar2[0][0] # rows = 0th column= 0th

0

In [14]:
ar2[1][1] # iat of pandas

6

In [18]:
#array[rows,columns] # sub setting

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [19]:
ar2[0,0]

0

In [20]:
ar2[1,1]

6

In [21]:
ar2[2:,1:3]

array([[11, 12],
       [16, 17]])

In [24]:
ar2[2,3:]

array([13, 14])

In [26]:
ar2[0::2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [28]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
ar3=ar[0:5]

In [30]:
ar3

array([0, 1, 2, 3, 4])

In [31]:
L=[10,20,30]

In [32]:
type(L)

list

In [41]:
L[0:2]=100

TypeError: can only assign an iterable

In [40]:
L

[100, 200, 300, 30]

In [35]:
arr=np.array([10,20,30,40])

In [36]:
arr

array([10, 20, 30, 40])

In [37]:
arr[0:3]=100

In [38]:
arr

array([100, 100, 100,  40])

In [42]:
arr5=np.array([10,20,30,40,50,60,70])

In [43]:
arr5

array([10, 20, 30, 40, 50, 60, 70])

In [44]:
arr5_01=arr5[0:4]

In [45]:
arr5_01

array([10, 20, 30, 40])

In [46]:
arr5_01[0:]=400

In [47]:
arr5_01

array([400, 400, 400, 400])

In [48]:
arr5

array([400, 400, 400, 400,  50,  60,  70])

In [49]:
arr6=arr5.copy()

In [50]:
arr6

array([400, 400, 400, 400,  50,  60,  70])

In [51]:
arr5

array([400, 400, 400, 400,  50,  60,  70])

In [52]:
arr6[5:]=999

In [53]:
arr6

array([400, 400, 400, 400,  50, 999, 999])

In [54]:
arr5

array([400, 400, 400, 400,  50,  60,  70])

In [55]:
# Boolean Methods

In [64]:
arr7=np.arange(1,26).reshape(5,5)
arr7

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [57]:
arr7

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [66]:
bol_val=arr7>10

In [67]:
arr7[bol_val]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [68]:
arr7

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [70]:
arr8=np.linspace(1,1000,num=25)

In [72]:
arr8=arr8.reshape(5,5)

In [73]:
arr8

array([[   1.   ,   42.625,   84.25 ,  125.875,  167.5  ],
       [ 209.125,  250.75 ,  292.375,  334.   ,  375.625],
       [ 417.25 ,  458.875,  500.5  ,  542.125,  583.75 ],
       [ 625.375,  667.   ,  708.625,  750.25 ,  791.875],
       [ 833.5  ,  875.125,  916.75 ,  958.375, 1000.   ]])

In [74]:
arr7+arr8

array([[   2.   ,   44.625,   87.25 ,  129.875,  172.5  ],
       [ 215.125,  257.75 ,  300.375,  343.   ,  385.625],
       [ 428.25 ,  470.875,  513.5  ,  556.125,  598.75 ],
       [ 641.375,  684.   ,  726.625,  769.25 ,  811.875],
       [ 854.5  ,  897.125,  939.75 ,  982.375, 1025.   ]])

In [75]:
arr7-arr8

array([[   0.   ,  -40.625,  -81.25 , -121.875, -162.5  ],
       [-203.125, -243.75 , -284.375, -325.   , -365.625],
       [-406.25 , -446.875, -487.5  , -528.125, -568.75 ],
       [-609.375, -650.   , -690.625, -731.25 , -771.875],
       [-812.5  , -853.125, -893.75 , -934.375, -975.   ]])

In [76]:
arr7*arr8

array([[1.000000e+00, 8.525000e+01, 2.527500e+02, 5.035000e+02,
        8.375000e+02],
       [1.254750e+03, 1.755250e+03, 2.339000e+03, 3.006000e+03,
        3.756250e+03],
       [4.589750e+03, 5.506500e+03, 6.506500e+03, 7.589750e+03,
        8.756250e+03],
       [1.000600e+04, 1.133900e+04, 1.275525e+04, 1.425475e+04,
        1.583750e+04],
       [1.750350e+04, 1.925275e+04, 2.108525e+04, 2.300100e+04,
        2.500000e+04]])

In [77]:
arr7/arr8

array([[1.        , 0.04692082, 0.03560831, 0.03177756, 0.02985075],
       [0.02869097, 0.02791625, 0.02736212, 0.02694611, 0.0266223 ],
       [0.02636309, 0.02615091, 0.02597403, 0.0258243 , 0.02569593],
       [0.02558465, 0.02548726, 0.02540131, 0.02532489, 0.02525651],
       [0.02519496, 0.02513927, 0.02508863, 0.02504239, 0.025     ]])

In [78]:
1/arr7

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667],
       [0.0625    , 0.05882353, 0.05555556, 0.05263158, 0.05      ],
       [0.04761905, 0.04545455, 0.04347826, 0.04166667, 0.04      ]])

In [79]:
np.dot(arr7,arr8)

array([[ 8340.   ,  8964.375,  9588.75 , 10213.125, 10837.5  ],
       [18771.25 , 20436.25 , 22101.25 , 23766.25 , 25431.25 ],
       [29202.5  , 31908.125, 34613.75 , 37319.375, 40025.   ],
       [39633.75 , 43380.   , 47126.25 , 50872.5  , 54618.75 ],
       [50065.   , 54851.875, 59638.75 , 64425.625, 69212.5  ]])

In [84]:
#np.add()
#np.substract()
np.sin(arr7)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [85]:
np.cos(arr7)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791],
       [-0.95765948, -0.27516334,  0.66031671,  0.98870462,  0.40808206],
       [-0.54772926, -0.99996083, -0.53283302,  0.42417901,  0.99120281]])

In [86]:
np.tan(arr7)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01],
       [ 3.00632242e-01,  3.49391565e+00, -1.13731371e+00,
         1.51589471e-01,  2.23716094e+00],
       [-1.52749853e+00,  8.85165604e-03,  1.58815308e+00,
        -2.13489670e+00, -1.33526407e-01]])